"""Initial schema

Revision ID: e188c645de6e
Revises: 
Create Date: 2026-02-26 22:19:21.900770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e188c645de6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headline')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('intraday_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('volume_multiplier', sa.Float(), nullable=False),
    sa.Column('is_below_vwap', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intraday_signals_id'), 'intraday_signals', ['id'], unique=False)
    op.create_index(op.f('ix_intraday_signals_sector'), 'intraday_signals', ['sector'], unique=False)
    op.create_table('sector_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('macro_trigger', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('bias', sa.Enum('Bullish', 'Bearish', 'Neutral', name='biasenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_mappings_id'), 'sector_mappings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('plan_type', sa.Enum('Free', 'Starter', 'Pro', name='plantypeenum'), nullable=False),
    sa.Column('subscription_status', sa.Enum('Active', 'Inactive', 'Trial', name='substatusenum'), nullable=False),
    sa.Column('trial_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('classified_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('High', 'Medium', 'Low', name='severityenum'), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('affected_sectors', sa.JSON(), nullable=False),
    sa.Column('bias_direction', sa.Enum('Bullish', 'Bearish', 'Neutral', name='biasenum'), nullable=False),
    sa.Column('time_horizon', sa.Enum('Intraday', 'Swing', name='timehorizonenum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classified_signals_id'), 'classified_signals', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_sub_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_razorpay_sub_id'), 'subscriptions', ['razorpay_sub_id'], unique=True)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('alert_text', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['classified_signals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_id'), 'alert_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_logs_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_subscriptions_razorpay_sub_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_classified_signals_id'), table_name='classified_signals')
    op.drop_table('classified_signals')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sector_mappings_id'), table_name='sector_mappings')
    op.drop_table('sector_mappings')
    op.drop_index(op.f('ix_intraday_signals_sector'), table_name='intraday_signals')
    op.drop_index(op.f('ix_intraday_signals_id'), table_name='intraday_signals')
    op.drop_table('intraday_signals')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
